# Generated by Django 5.1.3 on 2025-07-15 11:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='quantidade',
            new_name='quantidade_volumes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='produto',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_agendado',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
