# Generated by Django 5.1.3 on 2025-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_quantidade_agendamento_quantidade_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='compareceu',
            field=models.BooleanField(default=False, verbose_name='Fornecedor compareceu?'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_entrada_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrada real'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações adicionais'),
        ),
    ]
