# Generated by Django 5.2.1 on 2025-09-10 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendamento_compareceu_agendamento_hora_entrada_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChegadaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('total_agendamentos', models.PositiveIntegerField(default=0)),
                ('total_chegados', models.PositiveIntegerField(default=0)),
                ('total_pendentes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='horario_agendado',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='compareceu',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora_entrada_real',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='quantidade_volumes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='status_entrega',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('chegado', 'Chegado')], default='pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='fornecedor',
            field=models.CharField(max_length=255),
        ),
    ]
