# Generated by Django 5.2.1 on 2025-09-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_chegadadiaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data',
            new_name='data_agendada',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='horario',
            new_name='hora_agendada',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='compareceu',
            field=models.BooleanField(default=False, verbose_name='Fornecedor compareceu?'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_entrada_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrada real'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações adicionais'),
        ),
        migrations.AddField(
            model_name='chegadadiaria',
            name='total_adiantados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chegadadiaria',
            name='total_atrasados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chegadadiaria',
            name='total_pontuais',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
