# Generated by Django 5.2.1 on 2025-09-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_data_agendamento_data_agendada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255, verbose_name='Nome do Representante')),
                ('fornecedor_marca', models.CharField(max_length=255, verbose_name='Fornecedor/Marca')),
                ('data_agendada', models.DateField(verbose_name='Data da Visita')),
                ('hora_agendada', models.TimeField(verbose_name='Horário da Visita')),
                ('comprador_responsavel', models.CharField(max_length=255, verbose_name='Comprador Responsável')),
                ('compareceu', models.BooleanField(default=False, verbose_name='Representante compareceu?')),
                ('hora_entrada_real', models.DateTimeField(blank=True, null=True, verbose_name='Hora de entrada real')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações adicionais')),
            ],
        ),
        migrations.AddField(
            model_name='chegadadiaria',
            name='total_representantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chegadadiaria',
            name='total_representantes_chegados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
